#!/bin/sh

yellow=$(tput setaf 228);
green=$(tput setaf 71);
white=$(tput setaf 15);
red=$(tput setaf 124);
bold=$(tput bold);
reset=$(tput sgr0);

# To add a color: echo "${color}"
echo "${reset}"

print_usage() {
  echo "${bold}${white}Usage: al-run [options] <project name> <config file path> <logger file path>  ${reset}"
}

print_help() {
  print_usage
  echo "\nOptions:\n"
  echo "-h"
  echo "    show brief help"
  echo "-d"
  echo "    run remote debugger on port 5005"
  echo "-p"
  echo "    port to run on"
  exit 0
}

debug=false
run_port='9000'

while getopts ':hdp:' opt; do
  case "${opt}" in
    h) print_help ;;
    d) debug=true ;;
    p) run_port=${OPTARG} ;;
    *) print_usage
       exit 1 ;;
  esac
done

shift "$((OPTIND - 1))"

if [ -z $1 ] || [ -z $2 ] || [ -z $3 ]; then
  print_usage
  exit 1
fi

project_name=$1
config_file=$2
logger_file=$3

debug_script=''

if [ "$debug" = true ]; then
  debug_script='-J-Xdebug -J-Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005'
fi

echo sbt \"project ${project_name}\" -J-Dconfig.file=${config_file} -J-Dlogger.file=${logger_file} ${debug_script} \"run ${run_port}\"
