#!/bin/sh

yellow=$(tput setaf 228);
green=$(tput setaf 71);
white=$(tput setaf 15);
red=$(tput setaf 124);
bold=$(tput bold);
reset=$(tput sgr0);

# To add a color: echo "${color}"
echo "${reset}"

print_usage() {
  echo "${bold}${white}Usage: al-run [options] <project name> <config file path> <logger file path>  ${reset}"
}

print_help() {
  print_usage
  echo "\nOptions:\n"
  echo "-h"
  echo "    show brief help"
  echo "-s"
  echo "    path to sfml source"
  exit 0
}

sfml_source_path='~/SFML'

while getopts ':hs:' opt; do
  case "${opt}" in
    h) print_help ;;
    s) sfml_source_path=${OPTARG} ;;
    *) print_usage
       exit 1 ;;
  esac
done

shift "$((OPTIND - 1))"

if [[ $OSTYPE == 'linux-gnu'* || $OSTYPE == 'cygwin'* ]]; then
	if [[ $OSTYPE == 'linux-gnueabihf' ]]; then
		PLATFORM=rpi
	else
		PLATFORM=linux
	fi
elif [[ $OSTYPE == 'darwin'* ]]; then
	PLATFORM=osx
elif [[ $OSTYPE == 'msys' || $OSTYPE == 'win32' ]]; then
	PLATFORM=windows
fi

install_mac() {
  if type xcode-select >&- && xpath=$( xcode-select --print-path ) &&
     test -d "${xpath}" && test -x "${xpath}";
  then
     echo "-> ${green}command line tools already installed${reset}";
  else
     echo "-> ${red}command line tools are not installed, installing now${reset}";
     xcode-select --install 2>&1;
  fi

  if which brew >/dev/null
  then
     echo "-> ${green}homebrew already installed${reset}";
  else
     echo "-> ${red}homebrew is not installed, installing now${reset}";
     /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)";
  fi

  if brew list | grep sfml >/dev/null
  then
     echo "-> ${green}sfml already installed${reset}";
  else
     echo "-> ${red}sfml is not installed, installing now${reset}";
     brew install sfml;
  fi

  if which cmake >/dev/null
  then
     echo "-> ${green}cmake already installed${reset}";
  else
     echo "-> ${red}cmake is not installed, installing now${reset}";
     brew install cmake;
  fi
}

install_pi() {
	# install sfml library itself
	sudo apt-get install libsfml-dev;

	# install deps
	sudo apt-get install cmake
	sudo apt-get install cmake-gui
	sudo apt-get install libflac-dev
	sudo apt-get install libogg-dev
	sudo apt-get install libvorbis-dev
	sudo apt-get install libopenal-dev
	sudo apt-get install libjpeg8-dev
	sudo apt-get install libfreetype6-dev
	sudo apt-get install libudev-dev
	sudo apt-get install libraspberrypi-dev

	if [ -d $sfml_source_path ];
	then
		 echo "-> ${green}found sfml, compiling${reset}";
	else
		 echo "-> ${red}sfml was not found, cloning to ~/SFML ${reset}";
	 	 git clone https://github.com/SFML/SFML.git ~/SFML/
	fi
	cmake -S ~/SFML/ -B ~/lib/SFMl/
	pwd=$PWD
	cd ~/lib/SFML/
	make
	cd $pwd
}

if [[ $PLATFORM == "osx" ]];
then
  echo "-> ${green}Platform type: Mac OS X${reset}";
  install_mac;
elif [[ $PLATFORM == "rpi" ]];
then
  echo "-> ${green}Platform type: Raspberry Pi${reset}";
  echo "Support for rasbian coming as update #1";
elif [[ $PLATFORM == "linux" ]];
then
  echo "-> ${green}Platform type: Linux${reset}";
  echo "Support for rasbian coming as update #2";
elif [[ $PLATFORM == "windows" ]];
then
  echo "-> ${red}Lol good luck Tim${reset}";
  echo "Support for windows unlikely unless you wish to contribute: https://github.com/djpeach/custom-bash-scripts";
fi
