#!/bin/sh

yellow=$(tput setaf 228);
green=$(tput setaf 71);
white=$(tput setaf 15);
red=$(tput setaf 124);
bold=$(tput bold);
reset=$(tput sgr0);

# To add a color: "\[${color}\]"

echo "${reset}"

if type xcode-select >&- && xpath=$( xcode-select --print-path ) &&
   test -d "${xpath}" && test -x "${xpath}";
then
   echo "-> ${green}command line tools already installed${reset}";
else
   echo "-> ${red}command line tools are not installed, installing now${reset}";
   xcode-select --install 2>&1;
fi

if which brew >/dev/null
then
   echo "-> ${green}homebrew already installed${reset}";
else
   echo "-> ${red}homebrew is not installed, installing now${reset}";
   /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)";
fi

if brew list | grep sfml >/dev/null
then
   echo "-> ${green}sfml already installed${reset}";
else
   echo "-> ${red}sfml is not installed, installing now${reset}";
   brew install sfml;
fi
